version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4000:80"
      - "8080:80"
  web-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./web-client
    volumes:
      - ./web-client:/app
  # mobile-client:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./mobileClient
  #   volumes:
  #     - ./mobile-client:/app
  api-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./api-server
    volumes:
      - ./api-server:/app
    depends_on:
      - mongo
      - redis
